### ISSUE TITLE
WARNING: Skipping user bind, non existent bind point (file) in container: '/usr/bin/nvidia-smi'

### ISSUE THREAD

**Issue by praateekmahajan** [marcc-hpc/pytorch#2]
Singularity build results in the error mentioned in title.

**Comment by marcc-hpc** [comment]
@praateekmahajan Thanks, in the Singularity file, I created an empty directory for `/usr/bin/nvidia-smi` where it should have been an empty file.

You can see the recommendation for users to do that here:
https://github.com/singularityware/singularity/issues/1182#issuecomment-381796545

I'm building a new one on Singularity Hub now for 0.4.0a0 (latest will be updated also).
